### ISSUE TITLE
Question Regarding Reward Function

### ISSUE THREAD

**Issue by eereenah-fast** [exalearn/covid-drug-design#9]
Hello, thanks for sharing your project! 

I wanted to ask something regarding the reward function. I've been looking at implementations of MolDQN and similar papers and I've seen people use binding energy (calculated by docking) instead of IC50. Is there any reason why the latter is better?

Thank you in advance and apologies for the trivial question.

**Comment by WardLT** [comment]
Thanks for the question! I'm glad that you are finding it useful.

We use the IC50 as it is _mostly_ from experimental data and captures effects related to both to whether a drug binds, whether it stays bound over time, and whether that affects the protein activity. There It comes with the disadvantage that the data is available in much smaller quantities and are from a variety of proteins that are not specifically those from nCoV-19. We are not sure if it is a better approach, but we took it to complement other activities from our US-DOE collaborators. 

Does that give you a better idea?

PS. Sorry for the slow reply. Currently getting my life in order before a short vacation :)

**Comment by eereenah-fast** [comment]
It does, thanks a lot for the reply! 
Have a nice vacation!:)
